# (PART) Uniform Data Representation {-} 

# The Common Data Model {#CommonDataModel}

Leads: Mui van Zandt & Clair Blacketer

Introduction

* Why OMOP/OHDSI
* Person-centric model
* Source values, standard concepts and source concepts
  * Vocabulary map query 
* Introduce patient story (Lauren endometriosis)
  * Description of her care
* Conceptual items
  * Patient-centric
 * Time, when do things happen? 
  * Cross-links, indications (we don’t know what disease a drug is meant to treat, person by person)
    * We can infer
  * Typical questions and confusions people run into
  * Reference is not in the data, look in the vocabulary for reference information
  * Design principles, adherence
Standardized Clinical Data Tables - do not restate the wiki here, they should be separate
* Person Table
    * Overview
      * Structure
      * Conventions
    * How would Lauren look?
ETC….similar section for each CDM table 

How the CDM evolves based on community input

Comparison of OMOP model to other models (VH suggestion)

