# (PART) Evidence Quality {-}

# Introduction to Evidence Quality {#EvidenceQuality}

*Chapter lead: Jon Duke*

> Loss of fidelity begins with the movement of data from the doctor’s brain to the medical record.

*Clem McDonald, MD*
*Director, Lister Hill Center for Biomedical Informatics*
*National Library of Medicine, USA*

How do we know if the results of a study are reliable?  Can they be trusted for use in clinical settings?  What about in regulatory decision-making?  Can they serve as a foundation for future research? Each time a new study is published or disseminated, readers must consider these questions, regardless of whether the work was a randomized controlled trial, an observational study, or other type of analysis.

One of the concerns that is often raised around observational studies and the use of "real world data" is the topic of data quality. As a community, OHDSI strives to take a holistic view on the subject of quality by focusing more broadly on the question of "evidence quality" rather than data quality alone.  Specifically, OHDSI seeks to recognize, evaluate, and optimize the diverse set of processes necessary to achieve the highest quality reproducible evidence from diverse data sources.  

As such, we frame the discussion of evidence quality by considering the following four dimensions:

* [Data Quality](DataQuality.html) (ie data validity)
* [Clinical Validity](ClinicalValidity.html)
* [Software Validity](SoftwareValidity.html)
* [Method Validity](MethodValidity.html)

In this chapter, we will review each of these components and discuss how OHDSI tools, conventions, and community support their evaluation and improvement.
