\mainmatter

# (PART) The OHDSI Community {-} 

# Mission, vision, values {#MissionVisionValues}

*Chapter lead: George Hripcsak* 

## Our Mission 

> To improve health by empowering a community to collaboratively generate the evidence that promotes better health decisions and better care. \index{mission}

Observational Health Data Sciences and Informatics (OHDSI, pronounced as “Odyssey”) is an open science collaborative whose mission is to improve health by empowering a community to collaboratively generate the evidence that promotes better health decisions and better care. 

## Our Vision 

> A world in which observational research produces a comprehensive understanding of health and disease. \index{vision}

OHDSI envisions a world in which observational research produces a comprehensive understanding of health and disease. Observational data are generated in the regular course of health care or as part of normal behavior, and they may be collected through health care systems and processes like electronic health records, insurance claims, and prescription services, or through methods like personal monitoring devices. Observational data are voluminous, representative of the world’s diversity, and reflect real-world practice, but because they are not generated by engineered experiments, they are subject to bias such as confounding so that causal conclusions must be drawn carefully. For example, does ibuprofen cause headaches? Because people take ibuprofen to treat headache pain, it will be difficult to tell whether ibuprofen is causing a headache or treating it, especially because the reporting of the timing of symptoms and drugs is often imperfect.

## Our Objectives 

* **Innovation**: Observational research is a field which will benefit greatly from disruptive thinking. We actively seek and encourage fresh methodological approaches in our work.

* **Reproducibility**: Accurate, reproducible, and well-calibrated evidence is necessary for health improvement.

* **Community**: Everyone is welcome to actively participate in OHDSI, whether you are a patient, a health professional, a researcher, or someone who simply believes in our cause. \index{community}

* **Collaboration**: We work collectively to prioritize and address the real world needs of our community’s participants.

* **Openness**: We strive to make all our community’s proceeds open and publicly accessible, including the methods, tools and the evidence that we generate.

* **Beneficence**: We seek to protect the rights of individuals and organizations within our community at all times.
\index{objectives}

OHDSI addresses the full pipeline of generating observational evidence: collecting data from around the world, translating data from many nations to a common form, developing new methods to draw causal conclusions, writing software that executes those methods on gigantic databases, writing user interfaces to help researchers run those methods, engaging clinical researchers to ask clinical questions, creating a network of researchers to help answer those questions, working together to interpret the evidence, and investing in the community to promote communication and diversity. OHDSI strives to make all its community’s proceeds open and publicly accessible, including the methods, tools, and evidence that it generates. This encourages broad participation and promotes trust. Through openness and appropriate methods, OHDSI strives to achieve reproducibility, generating accurate, repeatable, and well-calibrated evidence that is necessary for health improvement. Getting there requires innovation; it encourages disruptive thinking to bring fresh methodological approaches to the task of generating evidence. OHDSI succeeds through its community. Everyone is welcome to actively participate in OHDSI, be they a patient, a health professional, a researcher, or someone who simply believes in OHDSI’s cause. The community moves forward through collaboration to address the real world needs of our community’s participants. It gains the trust of the community through beneficence, protecting the rights of individuals and organizations within the community at all times.
Protecting privacy is a critical concern. OHDSI does not collect data centrally, but instead creates a federated database, which means each data source keeps its data local, following the laws and regulations under which the data were collected. Each site converts its data to the OMOP CDM, allowing researchers to distribute research questions across the network in the form of an OHDSI protocol so that sites can voluntarily run those protocols without local software development and return results to that researcher. They can then collaboratively interpret the evidence without ever having access to individual patient’s data.

OHDSI’s open science community approach, coupled with its open-source tools, has enabled tremendous advances in observational research. One of the first OHDSI network analyses examined treatment pathways across three chronic diseases: diabetes, depression, and hypertension. Published in the Proceedings of the National Academy of Science, it was one of the largest observational studies ever conducted, with results from 11 data sources covering more than 250 million patients and revealed tremendous geographic differences and patient heterogeneity in treatment choices that had never been previously observable. OHDSI has developed new statistical methods for confounding adjustment and evaluating the validity of observational evidence for causal inference, and has applied these approaches in multiple contexts, from an individual safety surveillance question in epilepsy to a large-scale population-level effect estimation study for comparative effectiveness of depression treatments. The OHDSI community has also established a framework for how to responsibly apply machine-learning algorithms to observational healthcare data, which has been applied across various therapeutic areas.

## Summary

```{block2, type='rmdsummary'}
- OHDSI's mission is to improve health by empowering a community to collaboratively generate the evidence that promotes better health decisions and better care.

- Our vision is a world in which observational research produces a comprehensive understanding of health and disease.

- This is achieved through out objectives of innovation, reproducibility, community, collaboration, openness, and beneficence.

```
