# OHDSI Network Research {#NetworkResearch}

Contributors: Greg Klebanov, Vojtech Huser, list others 

What is OHDSI Network?

* OHDSI Community and Network Research
* International Open Science Networks
  * OHDSI US
  * OHDSI EU and EHDEN
  * OHDSI APAC

OHDSI Network Study Process

* Goals
* Workflow Overview
* Structure of Studies
* Protocol and IRB issues
* Existing framework (de-identified [time shifted] OMOP dataset under existing IRB protocol
* Overcoming Network Study Challenges
  * Data Privacy, Security and Compliance
  * Data Quality
  * Running OHDSI Methods in Isolated Environment
  * OMOP CDM Versioning
  
Tools, Platforms and Study Automation
* OHDSI Methods support for Network Studies
* LEGEND (should we have it here?)
* OHDSI ARACHNE Network Platform

Opportunities, future trends and Roadmap

## OHDSI Network Study Examples

### Endometriosis study

An endometriosis characterization study (available at https://github.com/molliemckillop/Endometriosis-Phenotype-Characterization) works with two cohorts. They are defined in cohorts.csv file (see here https://github.com/molliemckillop/Endometriosis-Phenotype-Characterization/blob/master/inst/settings/cohorts.csv).

After creating a cohort table, it is populated by executing this command here by infering a name of a '.sql' file from the previously defined cohort file. A createCohorts function is executed next. (see https://github.com/molliemckillop/Endometriosis-Phenotype-Characterization/blob/master/R/createCohorts.R). An SQL file that is generated by Atlas populates the cohort table with specific person_ids that fulfill the cohort definition.


## Excercises

### Defining a cohort

Q: Study the code for the x study and determine whether the cohort definition is available on the public OHDSI server. It if it, what is the cohort ID there? 

A: 
