<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 14 Patient Level Prediction | The Book of OHDSI</title>
  <meta name="description" content="This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook." />
  <meta name="generator" content="bookdown 0.11.1 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 14 Patient Level Prediction | The Book of OHDSI" />
  <meta property="og:type" content="book" />
  <meta property="og:url" content="https://ohdsi.github.io/TheBookOfOhdsi/" />
  <meta property="og:image" content="https://ohdsi.github.io/TheBookOfOhdsi/images/Cover/Cover.png" />
  <meta property="og:description" content="This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook." />
  <meta name="github-repo" content="OHDSI/TheBookOfOhdsi" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 14 Patient Level Prediction | The Book of OHDSI" />
  
  <meta name="twitter:description" content="This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook." />
  <meta name="twitter:image" content="https://ohdsi.github.io/TheBookOfOhdsi/images/Cover/Cover.png" />

<meta name="author" content="Observational Health Data Science and Informatics" />


<meta name="date" content="2019-06-25" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon" />
<link rel="prev" href="PopulationLevelEstimation.html">
<link rel="next" href="EvidenceQuality.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />







<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-104086677-2"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-104086677-2');
</script>


<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">The Book of OHDSI</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#goals-of-this-book"><i class="fa fa-check"></i>Goals of this book</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#structure-of-the-book"><i class="fa fa-check"></i>Structure of the book</a></li>
</ul></li>
<li class="part"><span><b>I The OHDSI Community</b></span></li>
<li class="chapter" data-level="1" data-path="MissionVissionValues.html"><a href="MissionVissionValues.html"><i class="fa fa-check"></i><b>1</b> Mission, vision, values</a><ul>
<li class="chapter" data-level="1.1" data-path="MissionVissionValues.html"><a href="MissionVissionValues.html#our-mission"><i class="fa fa-check"></i><b>1.1</b> Our Mission</a></li>
<li class="chapter" data-level="1.2" data-path="MissionVissionValues.html"><a href="MissionVissionValues.html#our-vision"><i class="fa fa-check"></i><b>1.2</b> Our Vision</a></li>
<li class="chapter" data-level="1.3" data-path="MissionVissionValues.html"><a href="MissionVissionValues.html#our-objectives"><i class="fa fa-check"></i><b>1.3</b> Our Objectives</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="Collaborators.html"><a href="Collaborators.html"><i class="fa fa-check"></i><b>2</b> Collaborators</a></li>
<li class="chapter" data-level="3" data-path="OpenScience.html"><a href="OpenScience.html"><i class="fa fa-check"></i><b>3</b> Open Science</a><ul>
<li class="chapter" data-level="3.1" data-path="OpenScience.html"><a href="OpenScience.html#open-science"><i class="fa fa-check"></i><b>3.1</b> Open Science</a></li>
<li class="chapter" data-level="3.2" data-path="OpenScience.html"><a href="OpenScience.html#fair-guiding-principles"><i class="fa fa-check"></i><b>3.2</b> FAIR Guiding Principles</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="WhereToBegin.html"><a href="WhereToBegin.html"><i class="fa fa-check"></i><b>4</b> Where to begin</a></li>
<li class="part"><span><b>II Uniform Data Representation</b></span></li>
<li class="chapter" data-level="5" data-path="CommonDataModel.html"><a href="CommonDataModel.html"><i class="fa fa-check"></i><b>5</b> The Common Data Model</a><ul>
<li class="chapter" data-level="5.1" data-path="CommonDataModel.html"><a href="CommonDataModel.html#design-principles"><i class="fa fa-check"></i><b>5.1</b> Design Principles</a></li>
<li class="chapter" data-level="5.2" data-path="CommonDataModel.html"><a href="CommonDataModel.html#data-model-conventions"><i class="fa fa-check"></i><b>5.2</b> Data Model Conventions</a><ul>
<li class="chapter" data-level="5.2.1" data-path="CommonDataModel.html"><a href="CommonDataModel.html#model-conv"><i class="fa fa-check"></i><b>5.2.1</b> General conventions of the model</a></li>
<li class="chapter" data-level="5.2.2" data-path="CommonDataModel.html"><a href="CommonDataModel.html#general-conventions-of-schemas"><i class="fa fa-check"></i><b>5.2.2</b> General conventions of schemas</a></li>
<li class="chapter" data-level="5.2.3" data-path="CommonDataModel.html"><a href="CommonDataModel.html#general-conventions-of-data-tables"><i class="fa fa-check"></i><b>5.2.3</b> General conventions of data tables</a></li>
<li class="chapter" data-level="5.2.4" data-path="CommonDataModel.html"><a href="CommonDataModel.html#general-conventions-of-fields"><i class="fa fa-check"></i><b>5.2.4</b> General conventions of fields</a></li>
<li class="chapter" data-level="5.2.5" data-path="CommonDataModel.html"><a href="CommonDataModel.html#representation-of-content-through-concepts"><i class="fa fa-check"></i><b>5.2.5</b> Representation of content through Concepts</a></li>
<li class="chapter" data-level="5.2.6" data-path="CommonDataModel.html"><a href="CommonDataModel.html#difference-between-concept-ids-and-source-values"><i class="fa fa-check"></i><b>5.2.6</b> Difference between Concept IDs and Source Values</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="CommonDataModel.html"><a href="CommonDataModel.html#omop-cdm-standardized-tables"><i class="fa fa-check"></i><b>5.3</b> OMOP CDM Standardized Tables</a><ul>
<li class="chapter" data-level="5.3.1" data-path="CommonDataModel.html"><a href="CommonDataModel.html#running-example-endometriosis"><i class="fa fa-check"></i><b>5.3.1</b> Running Example: Endometriosis</a></li>
<li class="chapter" data-level="5.3.2" data-path="CommonDataModel.html"><a href="CommonDataModel.html#person"><i class="fa fa-check"></i><b>5.3.2</b> PERSON table</a></li>
<li class="chapter" data-level="5.3.3" data-path="CommonDataModel.html"><a href="CommonDataModel.html#observationPeriod"><i class="fa fa-check"></i><b>5.3.3</b> OBSERVATION_PERIOD table</a></li>
<li class="chapter" data-level="5.3.4" data-path="CommonDataModel.html"><a href="CommonDataModel.html#visitOccurrence"><i class="fa fa-check"></i><b>5.3.4</b> VISIT_OCCURRENCE</a></li>
<li class="chapter" data-level="5.3.5" data-path="CommonDataModel.html"><a href="CommonDataModel.html#conditionOccurrence"><i class="fa fa-check"></i><b>5.3.5</b> CONDITION_OCCURRENCE</a></li>
<li class="chapter" data-level="5.3.6" data-path="CommonDataModel.html"><a href="CommonDataModel.html#drugExposure"><i class="fa fa-check"></i><b>5.3.6</b> DRUG_EXPOSURE</a></li>
<li class="chapter" data-level="5.3.7" data-path="CommonDataModel.html"><a href="CommonDataModel.html#procedureOccurrence"><i class="fa fa-check"></i><b>5.3.7</b> PROCEDURE_OCCURRENCE</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="StandardizedVocabularies.html"><a href="StandardizedVocabularies.html"><i class="fa fa-check"></i><b>6</b> Standardized Vocabularies</a></li>
<li class="chapter" data-level="7" data-path="ExtractTransformLoad.html"><a href="ExtractTransformLoad.html"><i class="fa fa-check"></i><b>7</b> Extract Transform Load</a></li>
<li class="part"><span><b>III Data Analytics</b></span></li>
<li class="chapter" data-level="8" data-path="DataAnalyticsUseCases.html"><a href="DataAnalyticsUseCases.html"><i class="fa fa-check"></i><b>8</b> Data Analytics Use Cases</a><ul>
<li class="chapter" data-level="8.1" data-path="DataAnalyticsUseCases.html"><a href="DataAnalyticsUseCases.html#characterization"><i class="fa fa-check"></i><b>8.1</b> Characterization</a></li>
<li class="chapter" data-level="8.2" data-path="DataAnalyticsUseCases.html"><a href="DataAnalyticsUseCases.html#population-level-estimation"><i class="fa fa-check"></i><b>8.2</b> Population-level estimation</a></li>
<li class="chapter" data-level="8.3" data-path="DataAnalyticsUseCases.html"><a href="DataAnalyticsUseCases.html#patient-level-prediction"><i class="fa fa-check"></i><b>8.3</b> Patient-Level prediction</a></li>
<li class="chapter" data-level="8.4" data-path="DataAnalyticsUseCases.html"><a href="DataAnalyticsUseCases.html#limitations-of-observational-research"><i class="fa fa-check"></i><b>8.4</b> Limitations of observational research</a><ul>
<li class="chapter" data-level="8.4.1" data-path="DataAnalyticsUseCases.html"><a href="DataAnalyticsUseCases.html#missing-data"><i class="fa fa-check"></i><b>8.4.1</b> Missing data</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="OhdsiAnalyticsTools.html"><a href="OhdsiAnalyticsTools.html"><i class="fa fa-check"></i><b>9</b> OHDSI Analytics Tools</a><ul>
<li class="chapter" data-level="9.1" data-path="OhdsiAnalyticsTools.html"><a href="OhdsiAnalyticsTools.html#analysis-implementation"><i class="fa fa-check"></i><b>9.1</b> Analysis implementation</a></li>
<li class="chapter" data-level="9.2" data-path="OhdsiAnalyticsTools.html"><a href="OhdsiAnalyticsTools.html#analysis-strategy"><i class="fa fa-check"></i><b>9.2</b> Analysis strategy</a></li>
<li class="chapter" data-level="9.3" data-path="OhdsiAnalyticsTools.html"><a href="OhdsiAnalyticsTools.html#re-usable-artifacts"><i class="fa fa-check"></i><b>9.3</b> Re-usable artifacts</a></li>
<li class="chapter" data-level="9.4" data-path="OhdsiAnalyticsTools.html"><a href="OhdsiAnalyticsTools.html#atlas"><i class="fa fa-check"></i><b>9.4</b> ATLAS</a></li>
<li class="chapter" data-level="9.5" data-path="OhdsiAnalyticsTools.html"><a href="OhdsiAnalyticsTools.html#artifact-management"><i class="fa fa-check"></i><b>9.5</b> Artifact management</a></li>
<li class="chapter" data-level="9.6" data-path="OhdsiAnalyticsTools.html"><a href="OhdsiAnalyticsTools.html#security"><i class="fa fa-check"></i><b>9.6</b> Security</a><ul>
<li class="chapter" data-level="9.6.1" data-path="OhdsiAnalyticsTools.html"><a href="OhdsiAnalyticsTools.html#how-to-install"><i class="fa fa-check"></i><b>9.6.1</b> How to install</a></li>
</ul></li>
<li class="chapter" data-level="9.7" data-path="OhdsiAnalyticsTools.html"><a href="OhdsiAnalyticsTools.html#methods-library"><i class="fa fa-check"></i><b>9.7</b> Methods Library</a><ul>
<li class="chapter" data-level="9.7.1" data-path="OhdsiAnalyticsTools.html"><a href="OhdsiAnalyticsTools.html#support-for-multiple-analyses"><i class="fa fa-check"></i><b>9.7.1</b> Support for multiple analyses</a></li>
<li class="chapter" data-level="9.7.2" data-path="OhdsiAnalyticsTools.html"><a href="OhdsiAnalyticsTools.html#BigDataSupport"><i class="fa fa-check"></i><b>9.7.2</b> Big data support</a></li>
<li class="chapter" data-level="9.7.3" data-path="OhdsiAnalyticsTools.html"><a href="OhdsiAnalyticsTools.html#documentation"><i class="fa fa-check"></i><b>9.7.3</b> Documentation</a></li>
<li class="chapter" data-level="9.7.4" data-path="OhdsiAnalyticsTools.html"><a href="OhdsiAnalyticsTools.html#how-to-install-1"><i class="fa fa-check"></i><b>9.7.4</b> How to install</a></li>
</ul></li>
<li class="chapter" data-level="9.8" data-path="OhdsiAnalyticsTools.html"><a href="OhdsiAnalyticsTools.html#integrated-solutions"><i class="fa fa-check"></i><b>9.8</b> Integrated solutions</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="SqlAndR.html"><a href="SqlAndR.html"><i class="fa fa-check"></i><b>10</b> SQL and R</a><ul>
<li class="chapter" data-level="10.1" data-path="SqlAndR.html"><a href="SqlAndR.html#SqlRender"><i class="fa fa-check"></i><b>10.1</b> SqlRender</a><ul>
<li class="chapter" data-level="10.1.1" data-path="SqlAndR.html"><a href="SqlAndR.html#sql-parameterization"><i class="fa fa-check"></i><b>10.1.1</b> SQL parameterization</a></li>
<li class="chapter" data-level="10.1.2" data-path="SqlAndR.html"><a href="SqlAndR.html#translation-to-other-sql-dialects"><i class="fa fa-check"></i><b>10.1.2</b> Translation to other SQL dialects</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="SqlAndR.html"><a href="SqlAndR.html#DatabaseConnector"><i class="fa fa-check"></i><b>10.2</b> DatabaseConnector</a><ul>
<li class="chapter" data-level="10.2.1" data-path="SqlAndR.html"><a href="SqlAndR.html#creating-a-connection"><i class="fa fa-check"></i><b>10.2.1</b> Creating a connection</a></li>
<li class="chapter" data-level="10.2.2" data-path="SqlAndR.html"><a href="SqlAndR.html#querying"><i class="fa fa-check"></i><b>10.2.2</b> Querying</a></li>
<li class="chapter" data-level="10.2.3" data-path="SqlAndR.html"><a href="SqlAndR.html#querying-using-ffdf-objects"><i class="fa fa-check"></i><b>10.2.3</b> Querying using ffdf objects</a></li>
<li class="chapter" data-level="10.2.4" data-path="SqlAndR.html"><a href="SqlAndR.html#querying-different-platforms-using-the-same-sql"><i class="fa fa-check"></i><b>10.2.4</b> Querying different platforms using the same SQL</a></li>
<li class="chapter" data-level="10.2.5" data-path="SqlAndR.html"><a href="SqlAndR.html#inserting-tables"><i class="fa fa-check"></i><b>10.2.5</b> Inserting tables</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="SqlAndR.html"><a href="SqlAndR.html#QueryTheCdm"><i class="fa fa-check"></i><b>10.3</b> Querying the CDM</a></li>
<li class="chapter" data-level="10.4" data-path="SqlAndR.html"><a href="SqlAndR.html#using-the-vocabulary-when-querying"><i class="fa fa-check"></i><b>10.4</b> Using the vocabulary when querying</a></li>
<li class="chapter" data-level="10.5" data-path="SqlAndR.html"><a href="SqlAndR.html#querylibrary"><i class="fa fa-check"></i><b>10.5</b> QueryLibrary</a></li>
<li class="chapter" data-level="10.6" data-path="SqlAndR.html"><a href="SqlAndR.html#designing-a-simple-study"><i class="fa fa-check"></i><b>10.6</b> Designing a simple study</a><ul>
<li class="chapter" data-level="10.6.1" data-path="SqlAndR.html"><a href="SqlAndR.html#problem-definition"><i class="fa fa-check"></i><b>10.6.1</b> Problem definition</a></li>
<li class="chapter" data-level="10.6.2" data-path="SqlAndR.html"><a href="SqlAndR.html#exposure"><i class="fa fa-check"></i><b>10.6.2</b> Exposure</a></li>
<li class="chapter" data-level="10.6.3" data-path="SqlAndR.html"><a href="SqlAndR.html#outcome"><i class="fa fa-check"></i><b>10.6.3</b> Outcome</a></li>
<li class="chapter" data-level="10.6.4" data-path="SqlAndR.html"><a href="SqlAndR.html#time-at-risk"><i class="fa fa-check"></i><b>10.6.4</b> Time-at-risk</a></li>
</ul></li>
<li class="chapter" data-level="10.7" data-path="SqlAndR.html"><a href="SqlAndR.html#implementing-the-study-using-sql-and-r"><i class="fa fa-check"></i><b>10.7</b> Implementing the study using SQL and R</a><ul>
<li class="chapter" data-level="10.7.1" data-path="SqlAndR.html"><a href="SqlAndR.html#exposure-cohort"><i class="fa fa-check"></i><b>10.7.1</b> Exposure cohort</a></li>
<li class="chapter" data-level="10.7.2" data-path="SqlAndR.html"><a href="SqlAndR.html#outcome-cohort"><i class="fa fa-check"></i><b>10.7.2</b> Outcome cohort</a></li>
<li class="chapter" data-level="10.7.3" data-path="SqlAndR.html"><a href="SqlAndR.html#incidence-rate-calculation"><i class="fa fa-check"></i><b>10.7.3</b> Incidence rate calculation</a></li>
<li class="chapter" data-level="10.7.4" data-path="SqlAndR.html"><a href="SqlAndR.html#clean-up"><i class="fa fa-check"></i><b>10.7.4</b> Clean up</a></li>
<li class="chapter" data-level="10.7.5" data-path="SqlAndR.html"><a href="SqlAndR.html#compatibility"><i class="fa fa-check"></i><b>10.7.5</b> Compatibility</a></li>
</ul></li>
<li class="chapter" data-level="10.8" data-path="SqlAndR.html"><a href="SqlAndR.html#exercises"><i class="fa fa-check"></i><b>10.8</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="Cohorts.html"><a href="Cohorts.html"><i class="fa fa-check"></i><b>11</b> Building the building blocks: cohorts</a></li>
<li class="chapter" data-level="12" data-path="Characterization.html"><a href="Characterization.html"><i class="fa fa-check"></i><b>12</b> Characterization</a></li>
<li class="chapter" data-level="13" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html"><i class="fa fa-check"></i><b>13</b> Population-level estimation</a><ul>
<li class="chapter" data-level="13.1" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#CohortMethod"><i class="fa fa-check"></i><b>13.1</b> The cohort method design</a><ul>
<li class="chapter" data-level="13.1.1" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#propensity-scores"><i class="fa fa-check"></i><b>13.1.1</b> Propensity scores</a></li>
<li class="chapter" data-level="13.1.2" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#variable-selection"><i class="fa fa-check"></i><b>13.1.2</b> Variable selection</a></li>
<li class="chapter" data-level="13.1.3" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#caliper"><i class="fa fa-check"></i><b>13.1.3</b> Caliper</a></li>
<li class="chapter" data-level="13.1.4" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#overlap-preference-scores"><i class="fa fa-check"></i><b>13.1.4</b> Overlap: preference scores</a></li>
<li class="chapter" data-level="13.1.5" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#balance"><i class="fa fa-check"></i><b>13.1.5</b> Balance</a></li>
</ul></li>
<li class="chapter" data-level="13.2" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#the-self-controlled-cohort-design"><i class="fa fa-check"></i><b>13.2</b> The self-controlled cohort design</a></li>
<li class="chapter" data-level="13.3" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#the-case-control-design"><i class="fa fa-check"></i><b>13.3</b> The case-control design</a></li>
<li class="chapter" data-level="13.4" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#the-case-crossover-design"><i class="fa fa-check"></i><b>13.4</b> The case-crossover design</a></li>
<li class="chapter" data-level="13.5" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#the-self-controlled-case-series-design"><i class="fa fa-check"></i><b>13.5</b> The self-controlled case series design</a></li>
<li class="chapter" data-level="13.6" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#designing-a-hypertension-study"><i class="fa fa-check"></i><b>13.6</b> Designing a hypertension study</a><ul>
<li class="chapter" data-level="13.6.1" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#problem-definition-1"><i class="fa fa-check"></i><b>13.6.1</b> Problem definition</a></li>
<li class="chapter" data-level="13.6.2" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#target-and-comparator"><i class="fa fa-check"></i><b>13.6.2</b> Target and comparator</a></li>
<li class="chapter" data-level="13.6.3" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#outcome-1"><i class="fa fa-check"></i><b>13.6.3</b> Outcome</a></li>
<li class="chapter" data-level="13.6.4" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#time-at-risk-1"><i class="fa fa-check"></i><b>13.6.4</b> Time-at-risk</a></li>
<li class="chapter" data-level="13.6.5" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#model"><i class="fa fa-check"></i><b>13.6.5</b> Model</a></li>
<li class="chapter" data-level="13.6.6" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#study-summary"><i class="fa fa-check"></i><b>13.6.6</b> Study summary</a></li>
</ul></li>
<li class="chapter" data-level="13.7" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#implementing-the-study-using-atlas"><i class="fa fa-check"></i><b>13.7</b> Implementing the study using ATLAS</a><ul>
<li class="chapter" data-level="13.7.1" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#ComparisonSettings"><i class="fa fa-check"></i><b>13.7.1</b> Comparative cohort settings</a></li>
<li class="chapter" data-level="13.7.2" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#effect-estimation-analysis-settings"><i class="fa fa-check"></i><b>13.7.2</b> Effect estimation analysis settings</a></li>
<li class="chapter" data-level="13.7.3" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#evaluationSettings"><i class="fa fa-check"></i><b>13.7.3</b> Evaluation settings</a></li>
<li class="chapter" data-level="13.7.4" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#running-the-study-package"><i class="fa fa-check"></i><b>13.7.4</b> Running the study package</a></li>
</ul></li>
<li class="chapter" data-level="13.8" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#implementing-the-study-using-r"><i class="fa fa-check"></i><b>13.8</b> Implementing the study using R</a><ul>
<li class="chapter" data-level="13.8.1" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#cohort-instantiation"><i class="fa fa-check"></i><b>13.8.1</b> Cohort instantiation</a></li>
<li class="chapter" data-level="13.8.2" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#data-extraction"><i class="fa fa-check"></i><b>13.8.2</b> Data extraction</a></li>
<li class="chapter" data-level="13.8.3" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#defining-the-study-population"><i class="fa fa-check"></i><b>13.8.3</b> Defining the study population</a></li>
<li class="chapter" data-level="13.8.4" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#propensity-scores-1"><i class="fa fa-check"></i><b>13.8.4</b> Propensity scores</a></li>
<li class="chapter" data-level="13.8.5" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#outcome-models"><i class="fa fa-check"></i><b>13.8.5</b> Outcome models</a></li>
<li class="chapter" data-level="13.8.6" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#running-multiple-analyses"><i class="fa fa-check"></i><b>13.8.6</b> Running multiple analyses</a></li>
</ul></li>
<li class="chapter" data-level="13.9" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#studyOutputs"><i class="fa fa-check"></i><b>13.9</b> Study outputs</a><ul>
<li class="chapter" data-level="13.9.1" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#propensity-score-and-model"><i class="fa fa-check"></i><b>13.9.1</b> Propensity score and model</a></li>
<li class="chapter" data-level="13.9.2" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#covariate-balance"><i class="fa fa-check"></i><b>13.9.2</b> Covariate balance</a></li>
<li class="chapter" data-level="13.9.3" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#follow-up-and-power"><i class="fa fa-check"></i><b>13.9.3</b> Follow up and power</a></li>
<li class="chapter" data-level="13.9.4" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#kaplan-meier"><i class="fa fa-check"></i><b>13.9.4</b> Kaplan Meier</a></li>
<li class="chapter" data-level="13.9.5" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#effect-size-estimate"><i class="fa fa-check"></i><b>13.9.5</b> Effect size estimate</a></li>
</ul></li>
<li class="chapter" data-level="13.10" data-path="PopulationLevelEstimation.html"><a href="PopulationLevelEstimation.html#excercises"><i class="fa fa-check"></i><b>13.10</b> Excercises</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html"><i class="fa fa-check"></i><b>14</b> Patient Level Prediction</a><ul>
<li class="chapter" data-level="14.1" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#designing-a-hypertension-study-1"><i class="fa fa-check"></i><b>14.1</b> Designing a hypertension study</a><ul>
<li class="chapter" data-level="14.1.1" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#problem-definition-2"><i class="fa fa-check"></i><b>14.1.1</b> Problem definition</a></li>
<li class="chapter" data-level="14.1.2" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#study-population-definition"><i class="fa fa-check"></i><b>14.1.2</b> Study population definition</a></li>
<li class="chapter" data-level="14.1.3" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#model-development-settings"><i class="fa fa-check"></i><b>14.1.3</b> Model development settings</a></li>
<li class="chapter" data-level="14.1.4" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#model-evaluation"><i class="fa fa-check"></i><b>14.1.4</b> Model evaluation</a></li>
<li class="chapter" data-level="14.1.5" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#study-summary-1"><i class="fa fa-check"></i><b>14.1.5</b> Study summary</a></li>
</ul></li>
<li class="chapter" data-level="14.2" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#implementing-the-study-in-r"><i class="fa fa-check"></i><b>14.2</b> Implementing the study in R</a><ul>
<li class="chapter" data-level="14.2.1" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#cohort-instantiation-1"><i class="fa fa-check"></i><b>14.2.1</b> Cohort instantiation</a></li>
<li class="chapter" data-level="14.2.2" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#data-extraction-1"><i class="fa fa-check"></i><b>14.2.2</b> Data extraction</a></li>
<li class="chapter" data-level="14.2.3" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#additional-inclusion-criteria"><i class="fa fa-check"></i><b>14.2.3</b> Additional inclusion criteria</a></li>
<li class="chapter" data-level="14.2.4" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#model-development"><i class="fa fa-check"></i><b>14.2.4</b> Model Development</a></li>
</ul></li>
<li class="chapter" data-level="14.3" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#implementing-the-study-in-atlas"><i class="fa fa-check"></i><b>14.3</b> Implementing the study in ATLAS</a></li>
<li class="chapter" data-level="14.4" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#internal-validation"><i class="fa fa-check"></i><b>14.4</b> Internal validation</a><ul>
<li class="chapter" data-level="14.4.1" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#discrimination"><i class="fa fa-check"></i><b>14.4.1</b> Discrimination</a></li>
<li class="chapter" data-level="14.4.2" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#calibration"><i class="fa fa-check"></i><b>14.4.2</b> Calibration</a></li>
<li class="chapter" data-level="14.4.3" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#smooth-calibration"><i class="fa fa-check"></i><b>14.4.3</b> Smooth Calibration</a></li>
<li class="chapter" data-level="14.4.4" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#preference-distribution"><i class="fa fa-check"></i><b>14.4.4</b> Preference distribution</a></li>
<li class="chapter" data-level="14.4.5" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#predicted-probability-distribution"><i class="fa fa-check"></i><b>14.4.5</b> Predicted probability distribution</a></li>
<li class="chapter" data-level="14.4.6" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#test-train-similarity"><i class="fa fa-check"></i><b>14.4.6</b> Test-Train similarity</a></li>
<li class="chapter" data-level="14.4.7" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#variable-scatter-plot"><i class="fa fa-check"></i><b>14.4.7</b> Variable scatter plot</a></li>
<li class="chapter" data-level="14.4.8" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#precision-recall"><i class="fa fa-check"></i><b>14.4.8</b> Precision recall</a></li>
<li class="chapter" data-level="14.4.9" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#demographic-summary"><i class="fa fa-check"></i><b>14.4.9</b> Demographic summary</a></li>
</ul></li>
<li class="chapter" data-level="14.5" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#external-validation"><i class="fa fa-check"></i><b>14.5</b> External validation</a></li>
<li class="chapter" data-level="14.6" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#journal-paper-generation"><i class="fa fa-check"></i><b>14.6</b> Journal paper generation</a></li>
<li class="chapter" data-level="14.7" data-path="PatientLevelPrediction.html"><a href="PatientLevelPrediction.html#excercises-1"><i class="fa fa-check"></i><b>14.7</b> Excercises</a></li>
</ul></li>
<li class="part"><span><b>IV Evidence Quality</b></span></li>
<li class="chapter" data-level="15" data-path="EvidenceQuality.html"><a href="EvidenceQuality.html"><i class="fa fa-check"></i><b>15</b> Evidence Quality</a></li>
<li class="chapter" data-level="16" data-path="DataQuality.html"><a href="DataQuality.html"><i class="fa fa-check"></i><b>16</b> Data Quality</a><ul>
<li class="chapter" data-level="16.1" data-path="DataQuality.html"><a href="DataQuality.html#introduction"><i class="fa fa-check"></i><b>16.1</b> Introduction</a></li>
<li class="chapter" data-level="16.2" data-path="DataQuality.html"><a href="DataQuality.html#achilles-heel-tool"><i class="fa fa-check"></i><b>16.2</b> Achilles Heel tool</a><ul>
<li class="chapter" data-level="16.2.1" data-path="DataQuality.html"><a href="DataQuality.html#precomputed-analyses"><i class="fa fa-check"></i><b>16.2.1</b> Precomputed Analyses</a></li>
<li class="chapter" data-level="16.2.2" data-path="DataQuality.html"><a href="DataQuality.html#example-dq-check"><i class="fa fa-check"></i><b>16.2.2</b> Example DQ check</a></li>
<li class="chapter" data-level="16.2.3" data-path="DataQuality.html"><a href="DataQuality.html#overview-of-existing-dq-heel-checks"><i class="fa fa-check"></i><b>16.2.3</b> Overview of existing DQ Heel checks</a></li>
</ul></li>
<li class="chapter" data-level="16.3" data-path="DataQuality.html"><a href="DataQuality.html#study-specific-checks"><i class="fa fa-check"></i><b>16.3</b> Study-specific checks</a><ul>
<li class="chapter" data-level="16.3.1" data-path="DataQuality.html"><a href="DataQuality.html#outcomes"><i class="fa fa-check"></i><b>16.3.1</b> Outcomes</a></li>
<li class="chapter" data-level="16.3.2" data-path="DataQuality.html"><a href="DataQuality.html#laboratory-data"><i class="fa fa-check"></i><b>16.3.2</b> Laboratory data</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="17" data-path="ClinicalValidity.html"><a href="ClinicalValidity.html"><i class="fa fa-check"></i><b>17</b> Clinical Validity</a></li>
<li class="chapter" data-level="18" data-path="SoftwareValidity.html"><a href="SoftwareValidity.html"><i class="fa fa-check"></i><b>18</b> Software Validity</a><ul>
<li class="chapter" data-level="18.1" data-path="SoftwareValidity.html"><a href="SoftwareValidity.html#software-development-process"><i class="fa fa-check"></i><b>18.1</b> Software Development Process</a><ul>
<li class="chapter" data-level="18.1.1" data-path="SoftwareValidity.html"><a href="SoftwareValidity.html#source-code-management"><i class="fa fa-check"></i><b>18.1.1</b> Source Code Management</a></li>
<li class="chapter" data-level="18.1.2" data-path="SoftwareValidity.html"><a href="SoftwareValidity.html#documentation-1"><i class="fa fa-check"></i><b>18.1.2</b> Documentation</a></li>
<li class="chapter" data-level="18.1.3" data-path="SoftwareValidity.html"><a href="SoftwareValidity.html#availability-of-current-and-historical-archive-versions"><i class="fa fa-check"></i><b>18.1.3</b> Availability of Current and Historical Archive Versions</a></li>
<li class="chapter" data-level="18.1.4" data-path="SoftwareValidity.html"><a href="SoftwareValidity.html#maintenance-support-and-retirement"><i class="fa fa-check"></i><b>18.1.4</b> Maintenance, Support and Retirement</a></li>
<li class="chapter" data-level="18.1.5" data-path="SoftwareValidity.html"><a href="SoftwareValidity.html#qualified-personnel"><i class="fa fa-check"></i><b>18.1.5</b> Qualified Personnel</a></li>
<li class="chapter" data-level="18.1.6" data-path="SoftwareValidity.html"><a href="SoftwareValidity.html#physical-and-logical-security"><i class="fa fa-check"></i><b>18.1.6</b> Physical and Logical Security</a></li>
<li class="chapter" data-level="18.1.7" data-path="SoftwareValidity.html"><a href="SoftwareValidity.html#disaster-recovery"><i class="fa fa-check"></i><b>18.1.7</b> Disaster Recovery</a></li>
</ul></li>
<li class="chapter" data-level="18.2" data-path="SoftwareValidity.html"><a href="SoftwareValidity.html#testing"><i class="fa fa-check"></i><b>18.2</b> Testing</a><ul>
<li class="chapter" data-level="18.2.1" data-path="SoftwareValidity.html"><a href="SoftwareValidity.html#unit-test"><i class="fa fa-check"></i><b>18.2.1</b> Unit test</a></li>
</ul></li>
<li class="chapter" data-level="18.3" data-path="SoftwareValidity.html"><a href="SoftwareValidity.html#conclusions"><i class="fa fa-check"></i><b>18.3</b> Conclusions</a></li>
</ul></li>
<li class="chapter" data-level="19" data-path="MethodValidity.html"><a href="MethodValidity.html"><i class="fa fa-check"></i><b>19</b> Method Validity</a><ul>
<li class="chapter" data-level="19.1" data-path="MethodValidity.html"><a href="MethodValidity.html#design-specific-diagnostics"><i class="fa fa-check"></i><b>19.1</b> Design-specific diagnostics</a></li>
<li class="chapter" data-level="19.2" data-path="MethodValidity.html"><a href="MethodValidity.html#diagnostics-for-all-estimation"><i class="fa fa-check"></i><b>19.2</b> Diagnostics for all estimation</a><ul>
<li class="chapter" data-level="19.2.1" data-path="MethodValidity.html"><a href="MethodValidity.html#negative-controls"><i class="fa fa-check"></i><b>19.2.1</b> Negative controls</a></li>
<li class="chapter" data-level="19.2.2" data-path="MethodValidity.html"><a href="MethodValidity.html#positive-controls"><i class="fa fa-check"></i><b>19.2.2</b> Positive controls</a></li>
<li class="chapter" data-level="19.2.3" data-path="MethodValidity.html"><a href="MethodValidity.html#empirical-evaluation"><i class="fa fa-check"></i><b>19.2.3</b> Empirical evaluation</a></li>
<li class="chapter" data-level="19.2.4" data-path="MethodValidity.html"><a href="MethodValidity.html#p-value-calibration"><i class="fa fa-check"></i><b>19.2.4</b> P-value calibration</a></li>
<li class="chapter" data-level="19.2.5" data-path="MethodValidity.html"><a href="MethodValidity.html#confidence-interval-calibration"><i class="fa fa-check"></i><b>19.2.5</b> Confidence interval calibration</a></li>
<li class="chapter" data-level="19.2.6" data-path="MethodValidity.html"><a href="MethodValidity.html#replication-across-sites"><i class="fa fa-check"></i><b>19.2.6</b> Replication across sites</a></li>
<li class="chapter" data-level="19.2.7" data-path="MethodValidity.html"><a href="MethodValidity.html#sensitivity-analyses"><i class="fa fa-check"></i><b>19.2.7</b> Sensitivity analyses</a></li>
</ul></li>
<li class="chapter" data-level="19.3" data-path="MethodValidity.html"><a href="MethodValidity.html#method-validation-in-practice"><i class="fa fa-check"></i><b>19.3</b> Method validation in practice</a><ul>
<li class="chapter" data-level="19.3.1" data-path="MethodValidity.html"><a href="MethodValidity.html#selecting-negative-controls"><i class="fa fa-check"></i><b>19.3.1</b> Selecting negative controls</a></li>
<li class="chapter" data-level="19.3.2" data-path="MethodValidity.html"><a href="MethodValidity.html#including-controls"><i class="fa fa-check"></i><b>19.3.2</b> Including controls</a></li>
<li class="chapter" data-level="19.3.3" data-path="MethodValidity.html"><a href="MethodValidity.html#empirical-performance"><i class="fa fa-check"></i><b>19.3.3</b> Empirical performance</a></li>
<li class="chapter" data-level="19.3.4" data-path="MethodValidity.html"><a href="MethodValidity.html#p-value-calibration-1"><i class="fa fa-check"></i><b>19.3.4</b> P-value calibration</a></li>
<li class="chapter" data-level="19.3.5" data-path="MethodValidity.html"><a href="MethodValidity.html#calibrate-confidence-interval"><i class="fa fa-check"></i><b>19.3.5</b> Calibrate confidence interval</a></li>
<li class="chapter" data-level="19.3.6" data-path="MethodValidity.html"><a href="MethodValidity.html#between-database-heterogeneity"><i class="fa fa-check"></i><b>19.3.6</b> Between-database heterogeneity</a></li>
<li class="chapter" data-level="19.3.7" data-path="MethodValidity.html"><a href="MethodValidity.html#sensitivity-analyses-1"><i class="fa fa-check"></i><b>19.3.7</b> Sensitivity analyses</a></li>
</ul></li>
<li class="chapter" data-level="19.4" data-path="MethodValidity.html"><a href="MethodValidity.html#advanced-ohdsi-methods-benchmark"><i class="fa fa-check"></i><b>19.4</b> Advanced: OHDSI Methods Benchmark</a></li>
<li class="chapter" data-level="19.5" data-path="MethodValidity.html"><a href="MethodValidity.html#exercises-1"><i class="fa fa-check"></i><b>19.5</b> Exercises</a></li>
</ul></li>
<li class="part"><span><b>V OHDSI Studies</b></span></li>
<li class="chapter" data-level="20" data-path="StudySteps.html"><a href="StudySteps.html"><i class="fa fa-check"></i><b>20</b> Study steps</a></li>
<li class="chapter" data-level="21" data-path="NetworkResearch.html"><a href="NetworkResearch.html"><i class="fa fa-check"></i><b>21</b> OHDSI Network Research</a><ul>
<li class="chapter" data-level="21.1" data-path="NetworkResearch.html"><a href="NetworkResearch.html#ohdsi-network-study-examples"><i class="fa fa-check"></i><b>21.1</b> OHDSI Network Study Examples</a><ul>
<li class="chapter" data-level="21.1.1" data-path="NetworkResearch.html"><a href="NetworkResearch.html#endometriosis-study"><i class="fa fa-check"></i><b>21.1.1</b> Endometriosis study</a></li>
</ul></li>
<li class="chapter" data-level="21.2" data-path="NetworkResearch.html"><a href="NetworkResearch.html#excercises-2"><i class="fa fa-check"></i><b>21.2</b> Excercises</a><ul>
<li class="chapter" data-level="21.2.1" data-path="NetworkResearch.html"><a href="NetworkResearch.html#defining-a-cohort"><i class="fa fa-check"></i><b>21.2.1</b> Defining a cohort</a></li>
</ul></li>
</ul></li>
<li class="appendix"><span><b>Appendix</b></span></li>
<li class="chapter" data-level="A" data-path="Glossary.html"><a href="Glossary.html"><i class="fa fa-check"></i><b>A</b> Glossary</a></li>
<li class="chapter" data-level="B" data-path="CohortDefinitions.html"><a href="CohortDefinitions.html"><i class="fa fa-check"></i><b>B</b> Cohort definitions</a><ul>
<li class="chapter" data-level="B.1" data-path="CohortDefinitions.html"><a href="CohortDefinitions.html#AceInhibitors"><i class="fa fa-check"></i><b>B.1</b> ACE inhibitors</a></li>
<li class="chapter" data-level="B.2" data-path="CohortDefinitions.html"><a href="CohortDefinitions.html#AceInhibitorsMono"><i class="fa fa-check"></i><b>B.2</b> New users of ACE inhibitors as first-line monotherapy for hypertension</a></li>
<li class="chapter" data-level="B.3" data-path="CohortDefinitions.html"><a href="CohortDefinitions.html#Ami"><i class="fa fa-check"></i><b>B.3</b> Acute myocardial infarction (AMI)</a></li>
<li class="chapter" data-level="B.4" data-path="CohortDefinitions.html"><a href="CohortDefinitions.html#Angioedema"><i class="fa fa-check"></i><b>B.4</b> Angioedema</a></li>
<li class="chapter" data-level="B.5" data-path="CohortDefinitions.html"><a href="CohortDefinitions.html#ThiazidesMono"><i class="fa fa-check"></i><b>B.5</b> New users of Thiazide-like diuretics as first-line monotherapy for hypertension</a></li>
</ul></li>
<li class="chapter" data-level="C" data-path="NegativeControls.html"><a href="NegativeControls.html"><i class="fa fa-check"></i><b>C</b> Negative controls</a><ul>
<li class="chapter" data-level="C.1" data-path="NegativeControls.html"><a href="NegativeControls.html#AceiThzNsc"><i class="fa fa-check"></i><b>C.1</b> ACEi and THZ</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">The Book of OHDSI</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="PatientLevelPrediction" class="section level1">
<h1><span class="header-section-number">Chapter 14</span> Patient Level Prediction</h1>
<p><em>Chapter leads: Peter Rijnbeek &amp; Jenna Reps</em></p>
<p>Clinical decision making is a complicated task in which the clinician has to infer a diagnosis or treatment pathway based on the available medical history of the patient and the current clinical guidelines. Clinical prediction models have been developed to support this decision making process and are used in clinical practice in a wide spectrum of specialties. These models predict a diagnostic or prognostic outcome based on a combination of patient characteristics, e.g. demographic information, disease history, treatment history. The number of publications describing clinical prediction models has increased strongly over the last 10 years. An example is the Garvan model that predicts the 5-years and 10-years fractures risk in any elderly man or woman based on age, fracture history, fall history, bone mass density or weight <span class="citation">(Nguyen et al. <a href="#ref-nguyen2008">2008</a>)</span>. Many prediction models have been developed in patient subgroups at higher risk that need more intensive monitoring, e.g. the prediction of 30-day mortality after an acute myocardial described by <span class="citation">Lee et al. (<a href="#ref-lee1995">1995</a>)</span>. Also, many models have been developed for asymptomatic subjects in the population, e.g. the famous Framingham risk functions for cardiovascular disease <span class="citation">(Wilson et al. <a href="#ref-wilson1998">1998</a>)</span>, or the models for breast cancer screening <span class="citation">(Engel and Fischer <a href="#ref-engel2015">2015</a>)</span>.</p>
<p>Surprisingly, most currently used models are estimated using small datasets and contain a limited set of patient characteristics. For example, in a review of 102 prognostic models in traumatic brain injury showed that three quarters of the models were based on samples with less than 500 patients <span class="citation">(Perel et al. <a href="#ref-perel2006">2006</a>)</span>. This low sample size, and thus low statistical power, forces the data analyst to make stronger modelling assumptions. The selection of the often limited set of patient characteristics is strongly guided by the expert knowledge at hand. This contrasts sharply with the reality of modern medicine wherein patients generate a rich digital trail, which is well beyond the power of any medical practitioner to fully assimilate. Presently, health care is generating huge amount of patient-specific information contained in the Electronic Health Record (EHR). This includes structured data in the form of diagnose, medication, laboratory test results, and unstructured data contained in clinical narratives. Currently, it is unknown how much predictive accuracy can be gained by leveraging the large amount of data originating from the complete EHR of a patient.</p>
<p>Massive-scale, patient-specific predictive modeling has become reality due the OHDSI initiative in which the common data model (CDM) allows for uniform and transparent analysis at an unprecedented scale. These large standardized populations contain rich data to build highly predictive large-scale models and also provide immediate opportunity to serve large communities of patients who are in most need of improved quality of care. Such models can inform truly personalized medical care leading hopefully to sharply improved patient outcomes. Furthermore, these models could assist in the design and analysis of randomized controlled trials (RCT) by enabling a better patient stratification or can be utilized to adjust for confounding variables in observational research. More accurate prediction models contribute to targeting of treatment and to increasing cost-effectiveness of medical care.</p>
<p>Advances in machine learning for large dataset analysis have led to increased interest in applying patient-level prediction on this type of data. However, many published efforts in patient-level-prediction do not follow the model development guidelines, fail to perform extensive external validation, or provide insufficient model details that limits the ability of independent researchers to reproduce the models and perform external validation. This makes it hard to fairly evaluate the predictive performance of the models and reduces the likelihood of the model being used appropriately in clinical practice. To improve standards, several papers have been written detailing guidelines for best practices in developing and reporting prediction models.</p>
<p>The Transparent Reporting of a multivariable prediction model for Individual Prognosis Or Diagnosis (TRIPOD) statement<a href="#fn8" class="footnoteRef" id="fnref8"><sup>8</sup></a> provides clear recommendations for reporting prediction model development and validation and addresses some of the concerns related to transparency. However, data structure heterogeneity and inconsistent terminologies still make collaboration and model sharing difficult as different researchers are often required to write new code to extract the data from their databases and may define variables differently.</p>
<p>In our paper <span class="citation">(Reps et al. <a href="#ref-reps2018">2018</a>)</span>, we propose a standardised framework for patient-level prediction that utilizes the OMOP Common Data Model (CDM) and standardized vocabularies, and describe the open-source software that we developed implementing the framework’s pipeline. The framework is the first to support existing best practice guidelines and will enable open dissemination of models that can be extensively validated across the network of OHDSI collaborators.</p>
<p>Figure <a href="PatientLevelPrediction.html#fig:figure1">14.1</a>, illustrates the prediction problem we address. Among a population at risk, we aim to predict which patients at a defined moment in time (t = 0) will experience some outcome during a time-at-risk. Prediction is done using only information about the patients in an observation window prior to that moment in time.</p>
<div class="figure"><span id="fig:figure1"></span>
<img src="images/PatientLevelPrediction/Figure1.png" alt="The prediction problem." width="100%" />
<p class="caption">
Figure 14.1: The prediction problem.
</p>
</div>
<p>As shown in Table <a href="PatientLevelPrediction.html#tab:plpDesign">14.1</a>, to define a prediction problem we have to define t=0 by a target Cohort (T), the outcome we like to predict by an outcome cohort (O), and the time-at-risk (TAR). Furthermore, we have to make design choices for the model we like to develop, and determine the observational datasets to perform internal and external validation.</p>
<table>
<caption><span id="tab:plpDesign">Table 14.1: </span> Main design choices in a prediction design.</caption>
<colgroup>
<col width="24%" />
<col width="75%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">Choice</th>
<th align="left">Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Target cohort</td>
<td align="left">A cohort for whom we wish to predict</td>
</tr>
<tr class="even">
<td align="left">Outcome cohort</td>
<td align="left">A cohort representing the outcome we wish to predict</td>
</tr>
<tr class="odd">
<td align="left">Time-at-risk</td>
<td align="left">For what time relative to t=0 do we want to make the prediction?</td>
</tr>
<tr class="even">
<td align="left">Model</td>
<td align="left">What algorithms using which parameters do we want use, and what predictor variables do we want to include?</td>
</tr>
</tbody>
</table>
<p>This conceptual framework works for all type of prediction problems:</p>
<ul>
<li>Disease onset and progression
<ul>
<li><strong>Structure</strong>: Amongst patients who are newly diagnosed with <em>[a disease]</em>, who will go on to have <em>[another disease or complication]</em> within <em>[time horizon from diagnosis]</em>?</li>
<li><strong>Example</strong>: Among newly diagnosed atrial fibrilation patients, who will go on to have ischemic stroke in the next three years?</li>
</ul></li>
<li>Treatment choice
<ul>
<li><strong>Structure</strong>: Amongst patients with <em>[indicated disease]</em> who are treated with either <em>[treatment 1]</em> or <em>[treatment 2]</em>, which patients were treated with <em>[treatment 1]</em> (on day 0).</li>
<li><strong>Example</strong>: Among patients with atrial fibrilation who took either warfarin or rivaroxaban, which patients gets warfarin? (e.g. for a propensity model)</li>
</ul></li>
<li>Treatment response
<ul>
<li><strong>Structure</strong>: Amongst new users of <em>[a treatment]</em>, who will experience <em>[some effect]</em> in <em>[time window]</em> ?</li>
<li><strong>Example</strong>: Which patients with diabetes who start on metformin stay on metform for three years?</li>
</ul></li>
<li>Treatment safety
<ul>
<li><strong>Structure</strong>: Amongst new users of <em>[a treatment]</em>, who will experience <em>[adverse event]</em> in <em>[time window]</em>?</li>
<li><strong>Example</strong>: Amongst new users of warfarin, who will have a GI bleed in one year?</li>
</ul></li>
<li>Treatment adherence
<ul>
<li><strong>Structure</strong>: Amongst new users of <em>[a treatment]</em>, who will achieve <em>[adherence metric]</em> at <em>[time window]</em>?</li>
<li><strong>Example</strong>: Which patients with diabetes who start on metformin achieve &gt;=80% proportion of days covered at one year?</li>
</ul></li>
</ul>
<p>In the next sections we will explain the best practices for model specification, implementation, and evaluation using OHDSI’s Patient-Level Prediction (PLP) framework as guidance.</p>
<div id="designing-a-hypertension-study-1" class="section level2">
<h2><span class="header-section-number">14.1</span> Designing a hypertension study</h2>
<p>The first step is to clearly define the prediction problem. Interestingly, in many published papers the prediction problem is poorly defined, e.g. it is unclear how the index date (start of the target Cohort) is defined. A poorly defined prediction problem does not allow for external validation by others let alone implementation in clinical practice. In the PLP framework we have enforced that we have to define the prediction problem we like to address, in which population we will build the model, which model we will build and how we will evaluate its performance. In this section we will guide you through this process and we will use a “Treatment safety” prediction type as an example.</p>
<div id="problem-definition-2" class="section level3">
<h3><span class="header-section-number">14.1.1</span> Problem definition</h3>
<p>Angioedema is a well known side-effect of ACE inhibitors, and the incidence of angioedema reported in the labeling for ACE inhibitors is in the range of 0.1% to 0.7% <span class="citation">(Byrd, Adam, and Brown <a href="#ref-byrd_2006">2006</a>)</span>. Monitoring patients for this adverse effect is important, because although angioedema is rare, it may be life-threatening, leading to respiratory arrest and death <span class="citation">(Norman et al. <a href="#ref-norman_2013">2013</a>)</span>. Further, if angioedema is not initially recognized, it may lead to extensive and expensive workups before it is identified as a cause <span class="citation">(Norman et al. <a href="#ref-norman_2013">2013</a>; Thompson and Frable <a href="#ref-thompson_1993">1993</a>)</span>. Other than the higher risk among African-American patients, there are no known predisposing factors for the development of ACE inhibitor–related angioedema <span class="citation">(Byrd, Adam, and Brown <a href="#ref-byrd_2006">2006</a>)</span>. Most reactions occur within the first week or month of initial therapy and often within hours of the initial dose <span class="citation">(Cicardi et al. <a href="#ref-circardi_2004">2004</a>)</span>. However, some cases may occur years after therapy has begun <span class="citation">(O’Mara and O’Mara <a href="#ref-mara_1996">1996</a>)</span>.No diagnostic test is available that specifically identifies those at risk. If we could identify those at risk, doctors could act, for example by discontinuing the ACE inhibitorin favor of another hypertension drug.</p>
<p>We will apply the PLP framework to observational healthcare data to address the following patient-level prediction question:</p>
<blockquote>
<p>Amongst patients who have just started on an ACE inhibitor for the first time, who will experience angioedema in the following year?</p>
</blockquote>
</div>
<div id="study-population-definition" class="section level3">
<h3><span class="header-section-number">14.1.2</span> Study population definition</h3>
<p>The final study population in which we will develop our model is often a subset of the target population, because we will e.g. apply criteria that are dependent on T and O or we want to do sensitivity analyses with subpopulations of T. For this we have to answer the following questions:</p>
<ul>
<li><p><em>What is the minimum amount of observation time we require before the start of the target cohort?</em> This choice could depend on the available patient time in your training data, but also on the time you expect to be available in the data sources you want to apply the model on in the future. The longer the minimum observation time, the more baseline history time is available for each person to use for feature extraction, but the fewer patients will qualify for analysis. Moreover, there could be clinical reasons to choose a short or longer lookback period. For our example, we will use a prior history as lookback period (washout period).</p></li>
<li><p><em>Can patients enter the target cohort multiple times?</em> In the target cohort definition, a person may qualify for the cohort multiple times during different spans of time, for example if they had different episodes of a disease or separate periods of exposure to a medical product. The cohort definition does not necessarily apply a restriction to only let the patients enter once, but in the context of a particular patient-level prediction problem, a user may want to restrict the cohort to the first qualifying episode. In our example, a person can only enter the target cohort once since our criteria was based on first use of an ACE inhibitor.</p></li>
<li><p><em>Do we allow persons to enter the cohort if they experienced the outcome before?</em> Do we allow persons to enter the target cohort if they experienced the outcome before qualifying for the target cohort? Depending on the particular patient-level prediction problem, there may be a desire to predict ‘incident’ first occurrence of an outcome, in which case patients who have previously experienced the outcome are not ‘at-risk’ for having a first occurrence and therefore should be excluded from the target cohort. In other circumstances, there may be a desire to predict ‘prevalent’ episodes, whereby patients with prior outcomes can be included in the analysis and the prior outcome itself can be a predictor of future outcomes. For our prediction example, we will choose not to include those with prior angioedema.</p></li>
<li><p><em>How do we define the period in which we will predict our outcome relative to the target cohort start?</em> We actually have to make two decisions to answer that question. First, does the time-at-risk window start at the date of the start of the target cohort or later? Arguments to make it start later could be that you want to avoid outcomes that were entered late in the record that actually occurred before the start of the target cohort or you want to leave a gap where interventions to prevent the outcome could theoretically be implemented. Second, you need to define the time-at-risk by setting the risk window end, as some specification of days offset relative to the target cohort start or end dates. For our problem we will predict in a ‘time-at-risk’ window starting 1 day after the start of the target cohort up to 365 days later.</p></li>
<li><p><em>Do we require a minimum amount of time-at-risk?</em> We have to decide if we want to include patients that did not experience the outcome but did leave the database earlier than the end of our time-at-risk period. These patients may experience the outcome when we do not observe them. For our prediction problem we decide to answer this question with ‘Yes, require a mimimum time-at-risk’ for that reason. Furthermore, we have to decide if this constraint also applies to persons who experienced the outcome or we will include all persons with the outcome irrespective of their total time at risk. For example, if the outcome is death, then persons with the outcome are likely censored before the full time-at-risk period is complete.</p></li>
</ul>
</div>
<div id="model-development-settings" class="section level3">
<h3><span class="header-section-number">14.1.3</span> Model development settings</h3>
<p>To develop the model we have to decide which algorithm(s) we like to train. We see the selection of the best algorithm for a certain prediction problem as an empirical question, i.e. you need to let the data speak for itself and try different approaches to find the best one. There is no algorithm that will work best for all problems (no free lunch). In our framework we therefore aim to implement many algorithms. Furthermore, we made the system modular so you can add your own custom algorithms. This out-of-scope for this chapter but mode details can be found in the <em>AddingCustomAlgorithms</em> vignette in the <a href="https://ohdsi.github.io/PatientLevelPrediction/">PatientLevelPrediction</a> package.</p>
<p>Our framework currently contains the following algorithms to choose from:</p>
<dl>
<dt>Regularized Logistic Regression</dt>
<dd>Lasso logistic regression belongs to the family of generalized linear models, where a linear combination of the variables is learned and finally a logistic function maps the linear combination to a value between 0 and 1. The lasso regularization adds a cost based on model complexity to the objective function when training the model. This cost is the sum of the absolute values of the linear combination of the coefficients. The model automatically performs feature selection by minimizing this cost. We use the <a href="https://ohdsi.github.io/Cyclops/">Cyclops</a> (Cyclic coordinate descent for logistic, Poisson and survival analysis) package to perform large-scale regularized logistic regression. <strong>Hyper-parameters</strong>: var (starting variance), seed.
</dd>
<dt>Gradient boosting machines</dt>
<dd>Gradient boosting machines is a boosting ensemble technique and in our framework it combines multiple decision trees. Boosting works by iteratively adding decision trees but adds more weight to the data-points that are misclassified by prior decision trees in the cost function when training the next tree. We use Extreme Gradient Boosting, which is an efficient implementation of the gradient boosting framework implemented in the xgboost R package available from CRAN. <strong>Hyper-parameters</strong>: ntree (number of trees), max depth (max levels in tree), min rows (minimum data points in in node), learning rate, seed | mtry (number of features in each tree),ntree (number of trees), maxDepth (max levels in tree), minRows (minimum data points in in node),balance (balance class labels), seed.
</dd>
<dt>Random forest</dt>
<dd>Random forest is a bagging ensemble technique that combines multiple decision trees. The idea behind bagging is to reduce the likelihood of overfitting, by using weak classifiers, but combining multiple diverse weak classifiers into a strong classifier. Random forest accomplishes this by training multiple decision trees but only using a subset of the variables in each tree and the subset of variables differ between trees. Our packages uses the sklearn learn implementation of Random Forest in python. <strong>Hyper-parameters</strong>: mtry (number of features in each tree),ntree (number of trees), maxDepth (max levels in tree), minRows (minimum data points in in node),balance (balance class labels), seed.
</dd>
<dt>K-nearest neighbors</dt>
<dd>K-nearest neighbors (KNN) is an algorithm that uses some metric to find the K closest labelled data-points, given the specified metric, to a new unlabelled data-point. The prediction of the new data-points is then the most prevalent class of the K-nearest labelled data-points. There is a sharing limitation of KNN, as the model requires labelled data to perform the prediction on new data, and it is often not possible to share this data across data sites. We included the <a href="https://github.com/OHDSI/BigKnn">BigKnn</a> package developed in OHDSI which is a large scale k-nearest neighbor classifier. <strong>Hyper-parameters</strong>: k (number of neighbours), weighted (weight by inverse frequency).
</dd>
<dt>Naive Bayes</dt>
<dd>The Naive Bayes algorithm applies the Bayes’ theorem with the “naive” assumption of conditional independence between every pair of features given the value of the class variable. Based on the likelihood the data belongs to a class and the prior distribution of the class, a posterior distribution is obtained. <strong>Hyper-parameters</strong>: none.
</dd>
<dt>AdaBoost</dt>
<dd>AdaBoost is a boosting ensemble technique. Boosting works by iteratively adding classifiers but adds more weight to the data-points that are misclassified by prior classifiers in the cost function when training the next classifier. We use the sklearn “AdaboostClassifier” implementation in Python. <strong>Hyper-parameters</strong>: nEstimators (the maximum number of estimators at which boosting is terminated), learningRate (learning rate shrinks the contribution of each classifier by learning_rate. There is a trade-off between learningRate and nEstimators).
</dd>
<dt>Decision Tree</dt>
<dd>A decision tree is a classifier that partitions the variable space using individual tests selected using a greedy approach. It aims to find partitions that have the highest information gain to separate the classes. The decision tree can easily overfit by enabling a large number of partitions (tree depth) and often needs some regularization (e.g., pruning or specifying hyper-parameters that limit the complexity of the model). We use the sklearn “DecisionTreeClassifier” implementation in Python. <strong>Hyper-parameters</strong>: maxDepth (the maximum depth of the tree), minSamplesSplit,minSamplesLeaf, minImpuritySplit (threshold for early stopping in tree growth. A node will split if its impurity is above the threshold, otherwise it is a leaf.), seed,classWeight (“Balance”&quot; or “None”).
</dd>
<dt>Multilayer Perception</dt>
<dd>Neural networks containing multiple layers that weight their inputs using a non-linear function. The first layer is the input layer, the last layer is the output layer the between are the hidden layers. Neural networks are generally trained using feed forward back-propagation. This is when you go through the network with a data-point and calculate the error between the true label and predicted label, then go backwards through the network and update the linear function weights based on the error. <strong>Hyper-parameters</strong>: size (the number of hidden nodes), alpha (the l2 regularisation), seed.
</dd>
<dt>Deep Learning</dt>
<dd>Deep learning such as deep nets, convolutional neural networks or recurrent neural networks are similar to a neural network but have multiple hidden layers that aim to learn latent representations useful for prediction. In a seperate vignette in the <a href="https://ohdsi.github.io/PatientLevelPrediction/">PatientLevelPrediction</a> package we describe these models and hyper-parameters in more detail.
</dd>
</dl>
<p>Furthermore, we have to decide on the <strong>covariates</strong> that we will use to train our model. In our example, we like to add gender, age, all conditions, drugs and drug groups, and visit counts. We also have to specify in which time windows we will look and we decide to look in year before and any time prior.</p>
</div>
<div id="model-evaluation" class="section level3">
<h3><span class="header-section-number">14.1.4</span> Model evaluation</h3>
<p>Finally, we have to define how we will train and test our model on our data, i.e. how we perform <strong>internal validation</strong>. For this we have to decide how we divide our dataset in a training and testing dataset and how we randomly assign patients to these two sets. Dependent on the size of the training set we can decide how much data we like to use for training, typically this is a 75% - 25% split. If you have very large datasets you can use more data for training. To randomly assign patients to the training and testing set, there are two commonly used approaches:</p>
<ol style="list-style-type: decimal">
<li>split by person. In this case a random seed is used to assign the patient to either sets.</li>
<li>split by time. In this case a time point is used to split the persons, e.g. 75% of the data is before and 25% is after this date. The advantage of this is that you take into consideration that the health care system has changed over time.</li>
</ol>
<p>For our prediction model we decide to start with a Regularized Logistic Regression and will use the default parameters. We will do a 75%-25% split by person.</p>
</div>
<div id="study-summary-1" class="section level3">
<h3><span class="header-section-number">14.1.5</span> Study summary</h3>
<p>We now completely defined our study as shown in Table <a href="PatientLevelPrediction.html#tab:plpSummary">14.2</a>.</p>
<table>
<caption><span id="tab:plpSummary">Table 14.2: </span> Main design choices for our study.</caption>
<colgroup>
<col width="24%" />
<col width="75%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">Choice</th>
<th align="left">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Target cohort</td>
<td align="left">Patients who have just started on an ACE inhibitor for the first time.</td>
</tr>
<tr class="even">
<td align="left">Outcome cohort</td>
<td align="left">Angioedema.</td>
</tr>
<tr class="odd">
<td align="left">Time-at-risk</td>
<td align="left">1 day till 365 days from cohort start. We will require at least 364 days at risk.</td>
</tr>
<tr class="even">
<td align="left">Model</td>
<td align="left">Gradient Boosting Machine with hyper-parameters ntree: 5000, max depth: 4 or 7 or 10 and learning rate: 0.001 or 0.01 or 0.1 or 0.9. Covariates will include gender, age, conditions, drugs, drug groups, and visit count. Data split: 75% train - 25% test, randomly assigned by person.</td>
</tr>
</tbody>
</table>
<p>We define the target cohort as the first exposure to any ACE inhibitor. Patients are excluded if they have less than 365 days of prior observation time or have prior angioedema.</p>
</div>
</div>
<div id="implementing-the-study-in-r" class="section level2">
<h2><span class="header-section-number">14.2</span> Implementing the study in R</h2>
<p>Now we have completely designed our study we have to implement the study. This will be done using the <a href="https://ohdsi.github.io/PatientLevelPrediction/">PatientLevelPrediction</a> package to build patient-level predictive models. The package enables data extraction, model building, and model evaluation using data from databases that are translated into the OMOP CDM.</p>
<div id="cohort-instantiation-1" class="section level3">
<h3><span class="header-section-number">14.2.1</span> Cohort instantiation</h3>
<p>We first need to instantiate the target and outcome cohorts. Instantiating cohorts is described in Chapter <a href="Cohorts.html#Cohorts">11</a>. The Appendix provides the full definitions of the target (Appendix <a href="CohortDefinitions.html#AceInhibitors">B.1</a>) and outcome (Appendix <a href="CohortDefinitions.html#Angioedema">B.4</a>) cohorts. In this example we will assume the ACE inhibitors cohort has ID 1, and the angioedema cohort has ID 2.</p>
</div>
<div id="data-extraction-1" class="section level3">
<h3><span class="header-section-number">14.2.2</span> Data extraction</h3>
<p>We first need to tell R how to connect to the server. <a href="https://ohdsi.github.io/PatientLevelPrediction/"><code>PatientLevelPrediction</code></a> uses the <a href="https://ohdsi.github.io/DatabaseConnector/"><code>DatabaseConnector</code></a> package, which provides a function called <code>createConnectionDetails</code>. Type <code>?createConnectionDetails</code> for the specific settings required for the various database management systems (DBMS). For example, one might connect to a PostgreSQL database using this code:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(PatientLevelPrediction)
connDetails &lt;-<span class="st"> </span><span class="kw">createConnectionDetails</span>(<span class="dt">dbms =</span> <span class="st">&quot;postgresql&quot;</span>,
                                       <span class="dt">server =</span> <span class="st">&quot;localhost/ohdsi&quot;</span>,
                                       <span class="dt">user =</span> <span class="st">&quot;joe&quot;</span>,
                                       <span class="dt">password =</span> <span class="st">&quot;supersecret&quot;</span>)

cdmDbSchema &lt;-<span class="st"> &quot;my_cdm_data&quot;</span>
cohortsDbSchema &lt;-<span class="st"> &quot;scratch&quot;</span>
cohortsDbTable &lt;-<span class="st"> &quot;my_cohorts&quot;</span>
cdmVersion &lt;-<span class="st"> &quot;5&quot;</span></code></pre></div>
<p>The last four lines define the <code>cdmDbSchema</code>, <code>cohortsDbSchema</code>, and <code>cohortsDbTable</code> variables, as well as the CDM version. We will use these later to tell R where the data in CDM format live, where the cohorts of interest have been created, and what version CDM is used. Note that for Microsoft SQL Server, database schemas need to specify both the database and the schema, so for example <code>cdmDbSchema &lt;- &quot;my_cdm_data.dbo&quot;</code>.</p>
<p>First it makes sense to verify that the cohort creation has succeeded, by counting the number of cohort entries:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">sql &lt;-<span class="st"> </span><span class="kw">paste</span>(<span class="st">&quot;SELECT cohort_definition_id, COUNT(*) AS count&quot;</span>,
<span class="st">&quot;FROM @cohortsDbSchema.cohortsDbTable&quot;</span>,
<span class="st">&quot;GROUP BY cohort_definition_id&quot;</span>)
conn &lt;-<span class="st"> </span><span class="kw">connect</span>(connDetails)
<span class="kw">renderTranslateQuerySql</span>(<span class="dt">connection =</span> conn, 
                        <span class="dt">sql =</span> sql,
                        <span class="dt">cohortsDbSchema =</span> cohortsDbSchema,
                        <span class="dt">cohortsDbTable =</span> cohortsDbTable)</code></pre></div>
<pre><code>##   cohort_definition_id  count
## 1                    1 527616
## 2                    2   3201</code></pre>
<p>Now we can tell <a href="https://ohdsi.github.io/PatientLevelPrediction/">PatientLevelPrediction</a> to extract all necessary data for our analysis. Covariates are extracted using the <a href="https://ohdsi.github.io/FeatureExtraction/"><code>FeatureExtraction</code></a> package. For more detailed information on the FeatureExtraction package see its vignettes. For our example study we decided to use these settings:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">covSettings &lt;-<span class="st"> </span><span class="kw">createCovariateSettings</span>(<span class="dt">useDemographicsGender =</span> <span class="ot">TRUE</span>,
                                       <span class="dt">useDemographicsAge =</span> <span class="ot">TRUE</span>,
                                       <span class="dt">useConditionGroupEraLongTerm =</span> <span class="ot">TRUE</span>,
                                       <span class="dt">useConditionGroupEraAnyTimePrior =</span> <span class="ot">TRUE</span>,
                                       <span class="dt">useDrugGroupEraLongTerm =</span> <span class="ot">TRUE</span>,
                                       <span class="dt">useDrugGroupEraAnyTimePrior =</span> <span class="ot">TRUE</span>,
                                       <span class="dt">useVisitConceptCountLongTerm =</span> <span class="ot">TRUE</span>,
                                       <span class="dt">longTermStartDays =</span> <span class="op">-</span><span class="dv">365</span>,
                                       <span class="dt">endDays =</span> <span class="op">-</span><span class="dv">1</span>)</code></pre></div>
<p>The final step for extracting the data is to run the <code>getPlpData</code> function and input the connection details, the database schema where the cohorts are stored, the cohort definition ids for the cohort and outcome, and the washoutPeriod which is the minimum number of days prior to cohort index date that the person must have been observed to be included into the data, and finally input the previously constructed covariate settings.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">plpData &lt;-<span class="st"> </span><span class="kw">getPlpData</span>(<span class="dt">connectionDetails =</span> connDetails,
                      <span class="dt">cdmDatabaseSchema =</span> cdmDbSchema,
                      <span class="dt">cohortDatabaseSchema =</span> cohortsDbSchema,
                      <span class="dt">cohortTable =</span> cohortsDbSchema,
                      <span class="dt">cohortId =</span> <span class="dv">1</span>,
                      <span class="dt">covariateSettings =</span> covariateSettings,
                      <span class="dt">outcomeDatabaseSchema =</span> cohortsDbSchema,
                      <span class="dt">outcomeTable =</span> cohortsDbSchema,
                      <span class="dt">outcomeIds =</span> <span class="dv">2</span>,
                      <span class="dt">sampleSize =</span> <span class="dv">10000</span>
)</code></pre></div>
<p>There are many additional parameters for the <code>getPlpData</code> function which are all documented in the <a href="https://ohdsi.github.io/PatientLevelPrediction/">PatientLevelPrediction</a> manual. The resulting <code>plpData</code> object uses the package <code>ff</code> to store information in a way that ensures R does not run out of memory, even when the data are large.</p>
<p>Creating the <code>plpData</code> object can take considerable computing time, and it is probably a good idea to save it for future sessions. Because <code>plpData</code> uses <code>ff</code>, we cannot use R’s regular save function. Instead, we’ll have to use the <code>savePlpData()</code> function:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">savePlpData</span>(plpData, <span class="st">&quot;angio_in_ace_data&quot;</span>)</code></pre></div>
<p>We can use the <code>loadPlpData()</code> function to load the data in a future session.</p>
</div>
<div id="additional-inclusion-criteria" class="section level3">
<h3><span class="header-section-number">14.2.3</span> Additional inclusion criteria</h3>
<p>To completely define the prediction problem the final study population is obtained by applying additional constraints on the two earlier defined cohorts, e.g., a minumim time at risk can be enforced (<code>requireTimeAtRisk, minTimeAtRisk</code>) and we can specify if this also applies to patients with the outcome (<code>includeAllOutcomes</code>). Here we also specify the start and end of the risk window relative to target cohort start. For example, if we like the risk window to start 30 days after the at-risk cohort start and end a year later we can set <code>riskWindowStart = 30</code> and <code>riskWindowEnd = 365</code>. In some cases the risk window needs to start at the cohort end date. This can be achieved by setting <code>addExposureToStart = TRUE</code> which adds the cohort (exposure) time to the start date.</p>
<p>In the example below all the settings we defined for our study are imposed:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">population &lt;-<span class="st"> </span><span class="kw">createStudyPopulation</span>(<span class="dt">plpData =</span> plpData,
                                    <span class="dt">outcomeId =</span> <span class="dv">2</span>,
                                    <span class="dt">washoutPeriod =</span> <span class="dv">364</span>,
                                    <span class="dt">firstExposureOnly =</span> <span class="ot">FALSE</span>,
                                    <span class="dt">removeSubjectsWithPriorOutcome =</span> <span class="ot">TRUE</span>,
                                    <span class="dt">priorOutcomeLookback =</span> <span class="dv">9999</span>,
                                    <span class="dt">riskWindowStart =</span> <span class="dv">1</span>,
                                    <span class="dt">riskWindowEnd =</span> <span class="dv">365</span>,
                                    <span class="dt">addExposureDaysToStart =</span> <span class="ot">FALSE</span>,
                                    <span class="dt">addExposureDaysToEnd =</span> <span class="ot">FALSE</span>,
                                    <span class="dt">minTimeAtRisk =</span> <span class="dv">364</span>,
                                    <span class="dt">requireTimeAtRisk =</span> <span class="ot">TRUE</span>,
                                    <span class="dt">includeAllOutcomes =</span> <span class="ot">TRUE</span>,
                                    <span class="dt">verbosity =</span> <span class="st">&quot;DEBUG&quot;</span>
)</code></pre></div>
</div>
<div id="model-development" class="section level3">
<h3><span class="header-section-number">14.2.4</span> Model Development</h3>
<p>In the set function of an algorithm the user can specify a list of eligible values for each hyper-parameter. All possible combinations of the hyper-parameters are included in a so-called grid search using cross-validation on the training set. If a user does not specify any value then the default value is used instead.</p>
<p>For example, if we use the following settings for the gradientBoostingMachine: ntrees=c(100,200), maxDepth=4 the grid search will apply the gradient boosting machine algorithm with ntrees=100 and maxDepth=4 plus the default settings for other hyper-parameters and ntrees=200 and maxDepth=4 plus the default settings for other hyper-parameters. The hyper-parameters that lead to the bestcross-validation performance will then be chosen for the final model. For our problem we choose to build a logistic regression model with the default hyper-parameters</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gbmModel &lt;-<span class="st"> </span><span class="kw">setGradientBoostingMachine</span>(<span class="dt">ntrees =</span> <span class="dv">5000</span>, 
                                       <span class="dt">maxDepth =</span> <span class="kw">c</span>(<span class="dv">4</span>,<span class="dv">7</span>,<span class="dv">10</span>), 
                                       <span class="dt">learnRate =</span> <span class="kw">c</span>(<span class="fl">0.001</span>,<span class="fl">0.01</span>,<span class="fl">0.1</span>,<span class="fl">0.9</span>))</code></pre></div>
<p>The <code>runPlP</code> function uses the population, <code>plpData</code>, and model settings to train and evaluate the model. We can use the testSplit (person/time) and testFraction parameters to split the data in a 75%-25% split and run the patient-level prediction pipeline:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gbmResults &lt;-<span class="st"> </span><span class="kw">runPlp</span>(<span class="dt">population =</span> population, 
                     <span class="dt">plpData =</span> plpData, 
                     <span class="dt">modelSettings =</span> gbmModel, 
                     <span class="dt">testSplit =</span> <span class="st">&#39;person&#39;</span>,
                     <span class="dt">testFraction =</span> <span class="fl">0.25</span>, 
                     <span class="dt">nfold =</span> <span class="dv">2</span>, 
                     <span class="dt">splitSeed =</span> <span class="dv">1234</span>)</code></pre></div>
<p>Under the hood the package will now use the R xgboost package to fit a a gradient boosting machine model using 75% of the data and will evaluate the model on the remaining 25%. A results data structure is returned containing information about the model, its performance etc.</p>
<p>In the <code>runPlp</code> function there are several parameters to save the <code>plpData</code>, <code>plpResults</code>, <code>plpPlots</code>, <code>evaluation</code>, etc. objects which are all set to <code>TRUE</code> by default.</p>
<p>You can save the model using:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">savePlpModel</span>(gbmResults<span class="op">$</span>model, <span class="dt">dirPath =</span> <span class="st">&quot;model&quot;</span>)</code></pre></div>
<p>You can load the model using:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">plpModel &lt;-<span class="st"> </span><span class="kw">loadPlpModel</span>(<span class="st">&quot;model&quot;</span>)</code></pre></div>
<p>You can also save the full results structure using:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">savePlpResult</span>(gbmResults, <span class="dt">location =</span> <span class="st">&quot;gbmResults&quot;</span>)</code></pre></div>
<p>To load the full results structure use:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">lrResults &lt;-<span class="st"> </span><span class="kw">loadPlpResult</span>(<span class="st">&quot;gbmResults&quot;</span>)</code></pre></div>
</div>
</div>
<div id="implementing-the-study-in-atlas" class="section level2">
<h2><span class="header-section-number">14.3</span> Implementing the study in ATLAS</h2>
<p>The script we created manually above can also be automatically created using a powerful feature in ATLAS. By creating a new prediction study (left menu) you can select the Target and Outcome as created in ATLAS, set all the study parameters, and then you can download a R package that you can use to execute your study. What is really powerful is that you can add multiple Ts, Os, covariate settings etc. The package will then run all the combinations of automatically as separate analyses. The screenshots below explain this process.</p>
<p><strong>Todo: add description of how to implement study using ATLAS</strong></p>
<p>By opening the R package in R studio and building the package you can run the study using the <code>execute</code> function. Theres is also an example <code>CodeToRun.R</code> script available in the <code>extras</code> folder of the package with extra instructions.</p>
</div>
<div id="internal-validation" class="section level2">
<h2><span class="header-section-number">14.4</span> Internal validation</h2>
<p>Once we execute the study, the <code>runPlp</code> function returns the trained model and the evaluation of the model on the train/test sets. You can interactively view the results by running: <code>viewPlp(runPlp = gbmResults)</code>. This will open a Shiny App in your browser in which you can view all performance measures created by the framework, including interactive plots, as shown in Figure <a href="#fig:shinysummary"><strong>??</strong></a>.</p>
<p><strong>Todo: update Shiny app screenshot with hypertension example</strong></p>
<p><img src="images/PatientLevelPrediction/shinysummary.png" width="100%" /></p>
<p>To generate and save all the evaluation plots to a folder run the following code:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plotPlp</span>(gbmResults, <span class="st">&quot;plots&quot;</span>)</code></pre></div>
<p>The plots are described in more detail in the next sections.</p>
<div id="discrimination" class="section level3">
<h3><span class="header-section-number">14.4.1</span> Discrimination</h3>
<p>The Receiver Operating Characteristics (ROC) plot shows the sensitivity against 1-specificity on the test set. The plot illustrates how well the model is able to discriminate between the people with the outcome and those without. The dashed diagonal line is the performance of a model that randomly assigns predictions. The higher the area under the ROC plot the better the discrimination of the model. Figure <a href="PatientLevelPrediction.html#fig:roc">14.2</a> is created by changing the probability threshold to assign the positive class.</p>
<p><strong>Todo: update plots with hypertension example</strong></p>
<div class="figure" style="text-align: center"><span id="fig:roc"></span>
<img src="images/PatientLevelPrediction/sparseROC.png" alt="The Receiver Operating Characteristics (ROC) curve." width="80%" />
<p class="caption">
Figure 14.2: The Receiver Operating Characteristics (ROC) curve.
</p>
</div>
</div>
<div id="calibration" class="section level3">
<h3><span class="header-section-number">14.4.2</span> Calibration</h3>
<p>The calibration plot (Figure <a href="PatientLevelPrediction.html#fig:plpCalibration">14.3</a>) shows how close the predicted risk is to the observed risk. The diagonal dashed line thus indicates a perfectly calibrated model. The ten (or fewer) dots represent the mean predicted values for each quantile plotted against the observed fraction of people in that quantile who had the outcome (observed fraction). The straight black line is the linear regression using these 10 plotted quantile mean predicted vs observed fraction points. The straight vertical lines represented the 95% lower and upper confidence intervals of the slope of the fitted line.</p>
<div class="figure" style="text-align: center"><span id="fig:plpCalibration"></span>
<img src="images/PatientLevelPrediction/sparseCalibration.png" alt="Calibration plot." width="90%" />
<p class="caption">
Figure 14.3: Calibration plot.
</p>
</div>
</div>
<div id="smooth-calibration" class="section level3">
<h3><span class="header-section-number">14.4.3</span> Smooth Calibration</h3>
<p>Similar to the traditional calibration shown above the Smooth Calibration plot shows the relationship between predicted and observed risk. the major difference is that the smooth fit allows for a more fine grained examination of this. Whereas the traditional plot will be heavily influenced by the areas with the highest density of data the smooth plot will provide the same information for this region as well as a more accurate interpretation of areas with lower density. the plot also contains information on the distribution of the outcomes relative to predicted risk.</p>
<p>However, the increased information gain comes at a computational cost. It is recommended to use the traditional plot for examination and then to produce the smooth plot for final versions. To create the smooth calibarion plot you have to run the follow command:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plotSmoothCalibration</span>(gbmResults)</code></pre></div>
<p>See the help function for more information, on how to set the smoothing method etc.</p>
<p>Figure <a href="PatientLevelPrediction.html#fig:plpSmoothCal">14.4</a> shows an example from another study that better demonstrates the impact of using a smooth calibration plot. The default line fit would not highlight the miss-calibration at the lower predicted probability levels that well.</p>
<div class="figure" style="text-align: center"><span id="fig:plpSmoothCal"></span>
<img src="images/PatientLevelPrediction/smoothCalibration.jpeg" alt="Smooth calibration plot." width="100%" />
<p class="caption">
Figure 14.4: Smooth calibration plot.
</p>
</div>
</div>
<div id="preference-distribution" class="section level3">
<h3><span class="header-section-number">14.4.4</span> Preference distribution</h3>
<p>The preference distribution plot (Figure <a href="PatientLevelPrediction.html#fig:plpPreference">14.5</a>) shows the preference score distributions for people in the test set with the outcome (red) without the outcome (blue).</p>
<div class="figure" style="text-align: center"><span id="fig:plpPreference"></span>
<img src="images/PatientLevelPrediction/preferencePDF.png" alt="Preference distribution plot." width="90%" />
<p class="caption">
Figure 14.5: Preference distribution plot.
</p>
</div>
</div>
<div id="predicted-probability-distribution" class="section level3">
<h3><span class="header-section-number">14.4.5</span> Predicted probability distribution</h3>
<p>The prediction distribution box plot shows the predicted risks of the people in the test set with the outcome (blue) and without the outcome (red).</p>
<p>The box plots in Figure <a href="PatientLevelPrediction.html#fig:plpPredProb">14.6</a> show that the predicted probability of the outcome is indeed higher for those with the outcome but there is also overlap between the two distribution which lead to an imperfect discrimination.</p>
<div class="figure" style="text-align: center"><span id="fig:plpPredProb"></span>
<img src="images/PatientLevelPrediction/predictionDistribution.png" alt="Predicted probability distribution." width="90%" />
<p class="caption">
Figure 14.6: Predicted probability distribution.
</p>
</div>
</div>
<div id="test-train-similarity" class="section level3">
<h3><span class="header-section-number">14.4.6</span> Test-Train similarity</h3>
<p>The test-train similarity is assessed by plotting the mean covariate values in the train set against those in the test set for people with and without the outcome.</p>
<p>The results in Figure <a href="PatientLevelPrediction.html#fig:plpTestTrain">14.7</a> for our example look very promising since the mean values of the covariates are on the diagonal.</p>
<div class="figure" style="text-align: center"><span id="fig:plpTestTrain"></span>
<img src="images/PatientLevelPrediction/generalizability.png" alt="Predicted probability distribution." width="100%" />
<p class="caption">
Figure 14.7: Predicted probability distribution.
</p>
</div>
</div>
<div id="variable-scatter-plot" class="section level3">
<h3><span class="header-section-number">14.4.7</span> Variable scatter plot</h3>
<p>The variable scatter plot shows the mean covariate value for the people with the outcome against the mean covariate value for the people without the outcome. The color of the dots corresponds to the inclusion (green) or exclusion in the model (blue), respectively. It is highly recommended to use the Shiny App since this allows you to hoover over a covariate to show more details (name, value etc).</p>
<p>Figure <a href="PatientLevelPrediction.html#fig:plpVarScatter">14.8</a> shows that the mean of most of the covariates is higher for subjects with the outcome compared to those without.</p>
<div class="figure" style="text-align: center"><span id="fig:plpVarScatter"></span>
<img src="images/PatientLevelPrediction/variableScatterplot.png" alt="Predicted probability distribution." width="100%" />
<p class="caption">
Figure 14.8: Predicted probability distribution.
</p>
</div>
</div>
<div id="precision-recall" class="section level3">
<h3><span class="header-section-number">14.4.8</span> Precision recall</h3>
<p>Precision (P) is defined as the number of true positives (TP) over the number of true positives plus the number of false positives (FP):</p>
<p><span class="math display">\[P\ =\frac{\ TP}{TP\ +\ FP}\]</span></p>
<p>Recall (R) is defined as the number of true positives over the number of true positives plus the number of false negatives (FN):</p>
<p><span class="math display">\[R\ =\frac{\ TP}{TP\ +\ FN}\]</span></p>
<p>These quantities are also related to the (F1) score, which is defined as the harmonic mean of precision and recall.</p>
<p><span class="math display">\[F1\ =\ 2\ \cdot\ \frac{P\cdot R}{P+R}\]</span></p>
<p>Note that the precision can either decrease or increase if the threshold is lowered. Lowering the threshold of a classifier may increase the denominator, by increasing the number of results returned. If the threshold was previously set too high, the new results may all be true positives, which will increase precision. If the previous threshold was about right or too low, further lowering the threshold will introduce false positives, decreasing precision. For Recall the denominator does not depend on the classifier threshold (Tp+Fn is a constant). This means that lowering the classifier threshold may increase recall, by increasing the number of true positive results. It is also possible that lowering the threshold may leave recall unchanged, while the precision fluctuates.</p>
<p>Figure <a href="PatientLevelPrediction.html#fig:plpPrecisionRecall">14.9</a> shows the tradeoff between precision and recall.</p>
<div class="figure" style="text-align: center"><span id="fig:plpPrecisionRecall"></span>
<img src="images/PatientLevelPrediction/precisionRecall.png" alt="Precision-recall plot." width="80%" />
<p class="caption">
Figure 14.9: Precision-recall plot.
</p>
</div>
</div>
<div id="demographic-summary" class="section level3">
<h3><span class="header-section-number">14.4.9</span> Demographic summary</h3>
<p>Figure <a href="PatientLevelPrediction.html#fig:plpDemoSummary">14.10</a> shows for females and males the expected and observed risk in different age groups together with a confidence area. The results show that our model is well calibrated across gender and age groups.</p>
<div class="figure" style="text-align: center"><span id="fig:plpDemoSummary"></span>
<img src="images/PatientLevelPrediction/demographicSummary.png" alt="Precision-recall plot." width="100%" />
<p class="caption">
Figure 14.10: Precision-recall plot.
</p>
</div>
</div>
</div>
<div id="external-validation" class="section level2">
<h2><span class="header-section-number">14.5</span> External validation</h2>
<p>We recommend to always perform external validation, i.e. apply the final model on as much new datasets as feasible and evaluate its performance. Here we assume the data extraction has already been peformed on a second database and stored in the <code>newData</code> folder. We load the model we previously fitted from the <code>model</code> folder:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># load the trained model</span>
plpModel &lt;-<span class="st"> </span><span class="kw">loadPlpModel</span>(<span class="st">&quot;model&quot;</span>)

<span class="co">#load the new plpData and create the population</span>
plpData &lt;-<span class="st"> </span><span class="kw">loadPlpData</span>(<span class="st">&quot;newData&quot;</span>)

population &lt;-<span class="st"> </span><span class="kw">createStudyPopulation</span>(<span class="dt">plpData =</span> plpData,
                                    <span class="dt">outcomeId =</span> <span class="dv">2</span>,
                                    <span class="dt">washoutPeriod =</span> <span class="dv">364</span>,
                                    <span class="dt">firstExposureOnly =</span> <span class="ot">FALSE</span>,
                                    <span class="dt">removeSubjectsWithPriorOutcome =</span> <span class="ot">TRUE</span>,
                                    <span class="dt">priorOutcomeLookback =</span> <span class="dv">9999</span>,
                                    <span class="dt">riskWindowStart =</span> <span class="dv">1</span>,
                                    <span class="dt">riskWindowEnd =</span> <span class="dv">365</span>,
                                    <span class="dt">addExposureDaysToStart =</span> <span class="ot">FALSE</span>,
                                    <span class="dt">addExposureDaysToEnd =</span> <span class="ot">FALSE</span>,
                                    <span class="dt">minTimeAtRisk =</span> <span class="dv">364</span>,
                                    <span class="dt">requireTimeAtRisk =</span> <span class="ot">TRUE</span>,
                                    <span class="dt">includeAllOutcomes =</span> <span class="ot">TRUE</span>
)

<span class="co"># apply the trained model on the new data</span>
validationResults &lt;-<span class="st"> </span><span class="kw">applyModel</span>(population, plpData, plpModel)</code></pre></div>
<p>To make things easier we also provide the <code>externalValidatePlp</code> function for performing external validation that also extracts the required data. This function is described in the package manual.</p>
</div>
<div id="journal-paper-generation" class="section level2">
<h2><span class="header-section-number">14.6</span> Journal paper generation</h2>
<p>We have added functionality to automatically generate a word document you can use as start of a journal paper. It contains many of the generated study details and results. If you have performed external validation these results will can be added as well. Optionally, you can add a “Table 1” that contains data on many covariates for the target population. You can create the draft journal paper by running this function:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"> <span class="kw">createPlpJournalDocument</span>(<span class="dt">plpResult =</span> <span class="op">&lt;</span>your plp results<span class="op">&gt;</span>,
                          <span class="dt">plpValidation =</span> <span class="op">&lt;</span>your validation results<span class="op">&gt;</span>,
                          <span class="dt">plpData =</span> <span class="op">&lt;</span>your plp data<span class="op">&gt;</span>,
                          <span class="dt">targetName =</span> <span class="st">&quot;&lt;target population&gt;&quot;</span>,
                          <span class="dt">outcomeName =</span> <span class="st">&quot;&lt;outcome&gt;&quot;</span>,
                          <span class="dt">table1 =</span> F,
                          <span class="dt">connectionDetails =</span> <span class="ot">NULL</span>,
                          <span class="dt">includeTrain =</span> <span class="ot">FALSE</span>,
                          <span class="dt">includeTest =</span> <span class="ot">TRUE</span>,
                          <span class="dt">includePredictionPicture =</span> <span class="ot">TRUE</span>,
                          <span class="dt">includeAttritionPlot =</span> <span class="ot">TRUE</span>,
                          <span class="dt">outputLocation =</span> <span class="st">&quot;&lt;your location&gt;&quot;</span>)</code></pre></div>
<p>For more details see the help page of the function.</p>
</div>
<div id="excercises-1" class="section level2">
<h2><span class="header-section-number">14.7</span> Excercises</h2>

</div>
</div>



<h3>References</h3>
<div id="refs" class="references">
<div id="ref-byrd_2006">
<p>Byrd, J. B., A. Adam, and N. J. Brown. 2006. “Angiotensin-converting enzyme inhibitor-associated angioedema.” <em>Immunol Allergy Clin North Am</em> 26 (4): 725–37.</p>
</div>
<div id="ref-circardi_2004">
<p>Cicardi, M., L. C. Zingale, L. Bergamaschini, and A. Agostoni. 2004. “Angioedema associated with angiotensin-converting enzyme inhibitor use: outcome after switching to a different treatment.” <em>Arch. Intern. Med.</em> 164 (8): 910–13.</p>
</div>
<div id="ref-engel2015">
<p>Engel, C., and C. Fischer. 2015. “Breast cancer risks and risk prediction models.” <em>Breast Care (Basel)</em> 10 (1): 7–12.</p>
</div>
<div id="ref-lee1995">
<p>Lee, K. L., L. H. Woodlief, E. J. Topol, W. D. Weaver, A. Betriu, J. Col, M. Simoons, P. Aylward, F. Van de Werf, and R. M. Califf. 1995. “Predictors of 30-day mortality in the era of reperfusion for acute myocardial infarction. Results from an international trial of 41,021 patients. GUSTO-I Investigators.” <em>Circulation</em> 91 (6): 1659–68.</p>
</div>
<div id="ref-nguyen2008">
<p>Nguyen, N. D., S. A. Frost, J. R. Center, J. A. Eisman, and T. V. Nguyen. 2008. “Development of prognostic nomograms for individualizing 5-year and 10-year fracture risks.” <em>Osteoporos Int</em> 19 (10): 1431–44.</p>
</div>
<div id="ref-norman_2013">
<p>Norman, J. L., W. L. Holmes, W. A. Bell, and S. W. Finks. 2013. “Life-threatening ACE inhibitor-induced angioedema after eleven years on lisinopril.” <em>J Pharm Pract</em> 26 (4): 382–88.</p>
</div>
<div id="ref-mara_1996">
<p>O’Mara, N. B., and E. M. O’Mara. 1996. “Delayed onset of angioedema with angiotensin-converting enzyme inhibitors: case report and review of the literature.” <em>Pharmacotherapy</em> 16 (4): 675–79.</p>
</div>
<div id="ref-perel2006">
<p>Perel, P., P. Edwards, R. Wentz, and I. Roberts. 2006. “Systematic review of prognostic models in traumatic brain injury.” <em>BMC Med Inform Decis Mak</em> 6 (November): 38.</p>
</div>
<div id="ref-reps2018">
<p>Reps, J. M., M. J. Schuemie, M. A. Suchard, P. B. Ryan, and P. R. Rijnbeek. 2018. “Design and implementation of a standardized framework to generate and evaluate patient-level prediction models using observational healthcare data.” <em>Journal of the American Medical Informatics Association</em> 25 (8): 969–75. doi:<a href="https://doi.org/10.1093/jamia/ocy032">10.1093/jamia/ocy032</a>.</p>
</div>
<div id="ref-thompson_1993">
<p>Thompson, T., and M. A. Frable. 1993. “Drug-induced, life-threatening angioedema revisited.” <em>Laryngoscope</em> 103 (1 Pt 1): 10–12.</p>
</div>
<div id="ref-wilson1998">
<p>Wilson, P. W., R. B. D’Agostino, D. Levy, A. M. Belanger, H. Silbershatz, and W. B. Kannel. 1998. “Prediction of coronary heart disease using risk factor categories.” <em>Circulation</em> 97 (18): 1837–47.</p>
</div>
</div>
<div class="footnotes">
<hr />
<ol start="8">
<li id="fn8"><p><a href="https://www.equator-network.org/reporting-guidelines/tripod-statement/" class="uri">https://www.equator-network.org/reporting-guidelines/tripod-statement/</a><a href="PatientLevelPrediction.html#fnref8">↩</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="PopulationLevelEstimation.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="EvidenceQuality.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/OHDSI/TheBookOfOhdsi/edit/master/PatientLevelPrediction.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"download": ["TheBookOfOhdsi.pdf", "TheBookOfOhdsi.epub"],
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
